### ISSUE TITLE
Zombies left after running the script

### ISSUE THREAD

**Issue by sfzhi** [troglobit/xplugd#1]
On Linux, after running the script upon receiving an event, the child processes keep hanging around as zombies. As far as I have observed, the number of zombies is one less that the number of processed events. This suggests that only the first child process termination is handled properly.
Indeed, in exec.c there is this line `signal(SIGCHLD, catch_child);`, which I believe is the cause of the problem. According to [signal(2)](http://man7.org/linux/man-pages/man2/signal.2.html), "The only portable use of signal() is to set a signal's disposition to SIG_DFL or SIG_IGN." What happens in this case is that the signal handler gets reset to default after the first shot. Whether that happens, depends on the OS and sometimes even on its version. That's why using signal(2) is strongly discouraged, in favor of sigaction(2).

**Comment by troglobit** [comment]
OK, never seen this myself on my Ubuntu installations.  How does your script/cmd look? Could be
useful to at least reproduce before fixing it.

I have a patch in my queue for this.  Have you tried fixing it yourself?

**Comment by sfzhi** [comment]
The script doesn't do much of anything. It's a one-line dummy that only logs the fact that it was called. Although, it shouldn't be relevant what it does. I fixed the issue for myself by changing the mentioned call to `signal(SIGCHLD, SIG_IGN)` - that does the job on Linux, but it's not portable either.

**Comment by troglobit** [comment]
Huh, funny I've never seen it before.  No bother, I'll try it out a bit to see if I can reproduce before pushing a fix.  Thanks for reporting!

**Comment by troglobit** [comment]
Cannot reproduce :disappointed: ... which is also why I was curious what you did.   I use about the same handling for reaping children in at least two other projects of mine: Finit and Inadyn.  So I get a bit worried about your report, hence my many questions.

What Linux distribution are you running on, and are you running the latest xplugd release (or even GIT maybe)?

**Comment by troglobit** [comment]
I hope it works better for you with the fix in 6fdc15b!  Unfortunately I've yet to reproduce -- maybe you got multiple script calls due to several simultaneous plug events.  Anyhow, with `SA_RESTART` it should work better.  Tthere's also a few other fixes committed to GIT master: e.g., unplug events for keyboard/mouse and a proper configure script.

**Comment by sfzhi** [comment]
To answer your question, I am using LFS-7.3, which includes glibc-2.17. According to the signal(2) manpage (towards the end of the "portability" section), to get the BSD behavior, that you were expecting and observing, one needs to define _DEFAULT_SOURCE on glibc-2.19 or newer and _BSD_SOURCE on older glibc. I can see the Makefile defines _DEFAULT_SOURCE, but apparently my glibc-2.17 doesn't understand that. If you tried a distribution with a newer glibc or one with some custom patches, it would explain why you couldn't reproduce the issue.

**Comment by troglobit** [comment]
@sfzhi I see, yes that would explain things.  Thank you for clarifying things for me!

The `_DEFAULT_SOURCE` vs `_BSD_SOURCE` issue was introduced very recently in GLIBC, I think it was 2.18, and it has caused quite a bit of portability problems for me in other projects as well.  Only way around it, on most occasions, was to have both defined, which is just plain nuts, but also very GNU.

In the latest master commits I've used `sigaction()` and `-D_POSIX_C_SOURCE=200809L` to get correct BSD behavior of the signal handler.

Again, thank you for the report! :+1:
