### ISSUE TITLE
possible issue recovering from suspend

### ISSUE THREAD

**Issue by dkwo** [troglobit/xplugd#5]
If I start from laptop docked, then suspend, undock, recover from suspend: it will correctly change screeens.
After this, if I suspend one more time (remaining undocked) then recover from suspend: the screen is not turned on (laptop is, as I can blindly unlock the screen-lock and then exit dwm and X).
This does not happen the other way round: if start from undocked, then dock, I can suspend as many times as I want. Similarly, if I run X/dwm from undocked then I can suspend as many times as I want, while staying undocked.
I'm using dwm on Arch Linux, xplugd is launched from .xinitrc by `xplugd` and my .xplugrc is
```
#!/bin/sh

type=$1
device=$2
status=$3
laptop=eDP-1
monitor=DP-2-1

case "$type,$device,$status" in
	display,$monitor,connected)
		xrandr --output $monitor --auto --dpi 163 --output $laptop --off
		nmcli r wifi off
		feh --bg-max ~/Pictures/bkground/*
		;;
	display,$monitor,disconnected)
                xrandr --output $monitor --off --output $laptop --auto --dpi 216
		xinput set-prop 14 305 1
		nmcli r wifi on
		feh --bg-max ~/Pictures/bkground/*
		;;
esac
```

**Comment by troglobit** [comment]
You don't seem to have a case for $laptop, connected.  So with that .xplugrc I guess you could end up in a situation when $laptop is turned off.  

On one of my laptops I have this, which treats each monitor separately; https://github.com/troglobit/awesome-config/blob/master/xplugrc

**Comment by dkwo** [comment]
Right, I don't, but that's because the only two events are monitor connected/disconnected, in which cases I also turn on/off laptop accordingly. Most of the times it works, with the exception that I mention. I could treat each monitor separately, but what's wrong with the present configuration? Sorry I just want to understand.

**Comment by troglobit** [comment]
Well, I dunno. Have you tried logging to a file all events you receive, i.e. before the case-statement?  It wouldn't surprise me if you either miss a 'display, eDP-1, connected' event or X never sends the event in the first place.

**Comment by dkwo** [comment]
I added a line `echo "$1 $2 $3" >> ~/Projects/xplugd.log` before cases:
Upon undocking I get
```
display DP-2-1 disconnected
keyboard 15 disconnected
keyboard 14 disconnected
pointer 16 disconnected
display eDP-1 connected
```
Upon docking
```
display DP-2-1 connected
display DP-2-2 disconnected
display DP-2-3 disconnected
display eDP-1 connected
display DP-2-1 connected
keyboard 15 connected
keyboard 14 connected
pointer 16 connected
```
while I do not get anything if I suspend while staying undocked, which is the case I have troubles with.

**Comment by troglobit** [comment]
Unfortunately I don't think this is an issue with xplugd, it just forwards X events to the script. If you don't get any event on resume and the screen remains dark it sounds more like a driver/hw issue than a problem with xplugd.

**Comment by dkwo** [comment]
Perhaps. What puzzles me is that this only happens if I resume after undocking.
